### ISSUE TITLE
How to repopulate

### ISSUE THREAD

**Issue by reweb-rferreyra** [metallurgical/jquery-metal-clone#11]
How to list cloned elements from a registered database list. I tried to do with foreach and add the remove button. But it did not work!

```php
<?php foreach ($fonts as $i => $font): $randonId = rand(); ?>
   <div class="<?php echo 'metalElement' . $randonId; ?>" data-clone-it>
    <div class="form-group">
        <?php echo form_dropdown('data[fonts][]', $fonts, $font, 'class="form-control"'); ?>
     </div>
     <?php if($i > 0): ?>
        <button type="button" class="<?php echo 'metalElement' . $randonId . 'BtnRemove'; ?> metal-btn-remove button button-danger button-block" style="margin-bottom: 20px" data-metal-ref="<?php echo '.metalElement' . $randonId; ?>">
              <i class="fa fa-trash-o"></i> 
                  Delete
               </button>
        <?php endif; ?>
    </div>
<?php endforeach;?>
```

**Comment by metallurgical** [comment]
You don't have to supply class name for button and cloned element as it will automatically generated for you. Anyway, let me re-produce it and will let you know later on. Thanks

**Comment by metallurgical** [comment]
This is the quickest solutions found so far that able to overcome your issue. You can do any modification using `callback` api provided.

```javascript
$('.to-clone:first').metalClone({
  btnClone: '#btnClone',
  onStart: function(element) {
    var regex = /(metalElement\d{0,})/g;
    var otherElem = $('.to-clone').not(element);
    
    otherElem.addClass(element.attr('class'));
    
    otherElem.append($('<button/>', {
      type: 'button',
      class: element.attr('class').match(regex) + 'BtnRemove metal-btn-remove',
      text: 'Remove',
      'data-metal-ref': '.' + element.attr('class').match(regex)
    }));
  }
})
```

This actually expected behaviour as you might have different 3 elements with the same class name but with different cloning section(should have 3 different areas of section, in your case having 1 section of cloning)

I've made an example to illustrate your problem:

https://jsfiddle.net/norlihazmeyGhazali/dzkp8wfh/

Hope this helpful. Thanks

**Comment by reweb-rferreyra** [comment]
@metallurgical Bravo! Thank you so much, it's working now!

**Comment by metallurgical** [comment]
You're welcome. Closing this issue now
